In [1]:
from __future__ import print_function
import torch

In [2]:
x = torch.empty(5,3)
print(x)

tensor([[-3.2103e-34,  4.5814e-41,  2.5560e+34],
        [ 3.0635e-41,  0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  4.6243e-44]])


In [3]:
x = torch.rand(5,3)
print(x)

tensor([[ 0.3293,  0.1781,  0.7458],
        [ 0.4335,  0.3811,  0.9914],
        [ 0.3034,  0.8424,  0.9287],
        [ 0.7693,  0.1915,  0.8800],
        [ 0.1124,  0.9672,  0.3846]])


In [4]:
x = torch.zeros(5,3,dtype = torch.long)
print(x)

tensor([[ 0,  0,  0],
        [ 0,  0,  0],
        [ 0,  0,  0],
        [ 0,  0,  0],
        [ 0,  0,  0]])


In [5]:
x = torch.tensor([5.5,3])
print(x)

tensor([ 5.5000,  3.0000])


In [6]:
x = x.new_ones(5,3,dtype = torch.double)
print(x)

tensor([[ 1.,  1.,  1.],
        [ 1.,  1.,  1.],
        [ 1.,  1.,  1.],
        [ 1.,  1.,  1.],
        [ 1.,  1.,  1.]], dtype=torch.float64)


In [7]:
x = torch.randn_like(x,dtype = torch.float)
print(x)

tensor([[-0.5017, -0.2614, -1.3357],
        [ 1.5142, -1.3014,  0.3402],
        [ 0.4172, -0.1527,  0.8979],
        [-0.4296,  0.0492,  0.5636],
        [-0.7317,  0.2383,  0.4990]])


In [8]:
print(x.size)

<built-in method size of Tensor object at 0x7fb66026b7e0>


In [9]:
print(x.size())

torch.Size([5, 3])


In [10]:
y = torch.rand(5,3)
print(x + y)

tensor([[ 0.3465, -0.1736, -0.7209],
        [ 2.1483, -0.5129,  1.2527],
        [ 1.3480,  0.8330,  1.4188],
        [ 0.0284,  0.7633,  0.8081],
        [-0.4656,  0.8069,  1.0928]])


In [11]:
print(torch.add(x,y))

tensor([[ 0.3465, -0.1736, -0.7209],
        [ 2.1483, -0.5129,  1.2527],
        [ 1.3480,  0.8330,  1.4188],
        [ 0.0284,  0.7633,  0.8081],
        [-0.4656,  0.8069,  1.0928]])


In [12]:
result = torch.empty(5,3)
torch.add(x,y,out = result)
print(result)

tensor([[ 0.3465, -0.1736, -0.7209],
        [ 2.1483, -0.5129,  1.2527],
        [ 1.3480,  0.8330,  1.4188],
        [ 0.0284,  0.7633,  0.8081],
        [-0.4656,  0.8069,  1.0928]])


In [13]:
y.add_(x)
print(y)

tensor([[ 0.3465, -0.1736, -0.7209],
        [ 2.1483, -0.5129,  1.2527],
        [ 1.3480,  0.8330,  1.4188],
        [ 0.0284,  0.7633,  0.8081],
        [-0.4656,  0.8069,  1.0928]])


In [17]:
print(x[1:,0])

tensor([ 1.5142,  0.4172, -0.4296, -0.7317])


In [23]:
x = torch.randn(4,4)
y = x.view(16)
z = x.view(-1,8)
print(x.size(),y.size(),z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


In [24]:
x = torch.randn(1)
print(x)
print(x.item())

tensor([ 1.8611])
1.8610692024230957


In [25]:
a = torch.ones(5)
print(a)

tensor([ 1.,  1.,  1.,  1.,  1.])


In [26]:
b = a.numpy()
print(b)

[ 1.  1.  1.  1.  1.]


In [27]:
a.add_(1)
print(a)
print(b)

tensor([ 2.,  2.,  2.,  2.,  2.])
[ 2.  2.  2.  2.  2.]


In [28]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a,1,out = a)
print(a)
print(b)

[ 2.  2.  2.  2.  2.]
tensor([ 2.,  2.,  2.,  2.,  2.], dtype=torch.float64)
